### PR TITLE
docs(app): Updated docs to demonstrate the usage of user-defined callback.

### LINKED ISSUE #28: Update documentation to include user defined callbacks
**Is your feature request related to a problem? Please describe.**
Updating the documentation to include the user-defined callback.

**Describe the solution you'd like**
Demonstrating the use of user-defined callback in the documentation

### PR DESCRIPTION
**Pull request by aniketbiswas21**
# Issue Related with PR
- fixes #28 

# Proposed Changes
- Updated documentation to reflect the usage of a user-defined callback function.

# Additional info if necessary
- none

# Checklist
- [x] Update README.md

### CODE REVIEW

**Comment by aniketbiswas21** [comment]
@YashKumarVerma Sir, Please take a look!

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma Sir, Please take a look!

Please don't call me as sir. Edit the body and remove the word please 🥺

**Review by YashKumarVerma — APPROVED** [review]

**Comment by aniketbiswas21** [comment]
> > @YashKumarVerma Sir, Please take a look!
> 
> Please don't call me as sir. Edit the body and remove the word please

Sure :rofl:

**Review by YashKumarVerma — APPROVED** [review]

**Comment by YashKumarVerma** [comment]
thanks !

**Pull request merged**
