### PR TITLE
fix(ci): fix ci tests

### LINKED ISSUE #30: Fix Failing CI tests for incoming pull requests
**Describe the bug**
Currently, the workflow fails for incoming pull requests.

**Expected behavior**
Workflow successfully runs on a pull request.

**Additional context**
I will be making a PR to fix this ASAP.

### PR DESCRIPTION
**Pull request by aniketbiswas21**
# Issue Related with PR
- fixes #30 

# Proposed Changes
- Fixed the workflow for incoming pull requests

# Additional info if necessary
- none

# Checklist
- [x] Fix CI Tests

### CODE REVIEW

**Comment by aniketbiswas21** [comment]
@YashKumarVerma The build tests are failing for example directory. Maybe because of missing packages in the example directory?

**Comment by aniketbiswas21** [comment]
@YashKumarVerma I fixed the failing tests. Please take a look!

**Comment by aniketbiswas21** [comment]
@YashKumarVerma Bhaiya, if you are free. Can you review this?

**Review by YashKumarVerma — APPROVED** [review]

**Comment by YashKumarVerma** [comment]
thanks !

**Pull request merged**
