### PR TITLE
feat(app): Add user defined callback

### LINKED ISSUE #6: Run a custom user defined function for any error
**Is your feature request related to a problem? Please describe.**
Allow user to define a function before on encountering an exception 

**Describe the solution you'd like**
 this the kind of feature you looking for
[
error:"",
message:""
function_to_run:""
]

### PR DESCRIPTION
**Pull request by aniketbiswas21**
# Issue Related with PR
- fixes #6 

# Proposed Changes
- Added an option to add an optional callback that runs after throwing an error 

# Additional info if necessary
- None

# Checklist
- [x] Option for user defined callback

### CODE REVIEW

**Comment by aniketbiswas21** [comment]
@YashKumarVerma Sir, Can you take a look?

And for the failing test, I believe that it is not able to checkout to the branch to run the following tests(not sure why)

**Review by YashKumarVerma — APPROVED** [review]
LGTM

**Comment by YashKumarVerma** [comment]
this is a cool feature !

**Comment by YashKumarVerma** [comment]
could you update the docs for it in a new PR @aniketbiswas21 ?

**Comment by aniketbiswas21** [comment]
> could you update the docs for it in a new PR @aniketbiswas21 ?

Yeah sure!

**Pull request merged**
